version: "3"

services:
  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000     
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin305
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres 

volumes:
  postgres_data:

networks:
  postgres: